/*
 * Diccionario de búsqueda para las fotos del catálogo: nombre en español
 * de cada grupo/categoría → término de búsqueda en inglés para Wikimedia
 * Commons, que indexa mejor en inglés. Se separa del script principal
 * porque es la parte que un humano va a querer ajustar sin tocar lógica
 * — si una foto no quedó bien, lo primero es probar otra consulta aquí
 * antes de sospechar del script.
 */
export const GROUP_QUERIES = {
  "Agua": "bottled drinking water",
  "Alimentos y Bebidas": "grocery food pantry",
  "Cobijas y Colchonetas": "blanket bedding folded",
  "Despensas Armadas": "food relief care package box",
  "Herramientas y Equipos": "hand tools set",
  "Higiene Personal": "personal hygiene products",
  "Limpieza del Hogar": "household cleaning supplies",
  "Mascotas": "pet supplies dog cat",
  "Materiales de Construcción": "construction building materials",
  "Medicamentos y Botiquines": "first aid medicine kit",
  "Ropa y Calzado": "folded clothing and shoes",
};

export const CATEGORY_QUERIES = {
  "Aceites y Vinagres": "cooking oil bottle",
  "Agua Embotellada": "bottled water pack",
  "Alimento para Mascotas": "dry pet food bag",
  "Analgésicos": "pain relief tablets pack",
  "Antidiarreicos": "medicine tablets blister pack",
  "Antigripales": "cold and flu medicine box",
  "Arroz y Legumbres": "rice grain bowl",
  "Avena y Cereales": "oats breakfast cereal",
  "Azúcar y Dulces": "sugar and candy",
  "Bebidas Frías": "cold soft drink bottles",
  "Bolsas de Agua": "sachet water plastic pouch",
  "Botiquines Armados": "first aid kit box",
  "Café y Bebidas Calientes": "coffee hot drink",
  "Calcetines": "pair of socks folded",
  "Calzado": "pair of sneakers shoes",
  "Cemento y Agregados": "cement bags construction",
  "Chiles y Salsas": "hot sauce bottle",
  "Cloro y Desinfectantes": "bleach disinfectant bottle",
  "Cobijas": "folded blanket",
  "Colchonetas": "sleeping mat pad",
  "Desodorante": "deodorant stick",
  "Despensas": "pantry food box",
  "Detergente": "laundry detergent",
  "Enlatados y Conservas": "canned food cans grocery shelf",
  "Equipos de Protección": "personal protective equipment",
  "Escobas y Trapos": "cleaning broom mop bucket",
  "Especias y Condimentos": "spice jars kitchen rack",
  "Galletas y Botanas": "cookies and snacks",
  "Herramientas Manuales": "hand tools",
  "Hielo": "ice cubes",
  "Jabón para Ropa": "laundry soap bar",
  "Jabón para Trastes": "dish washing soap",
  "Jabón y Shampoo": "soap and shampoo bottles",
  "Leche y Lácteos": "milk carton dairy products fresh",
  "Linternas y Pilas": "flashlight and batteries",
  "Láminas y Estructuras": "corrugated metal roofing sheets stacked",
  "Mantas y Abarrotas": "wool blanket folded",
  "Material de Curación": "adhesive bandage gauze medical supplies",
  "Pan y Cereales": "bread and cereal",
  "Pantalones": "folded denim jeans trousers",
  "Papel Higiénico": "toilet paper rolls",
  "Pasta de Dientes": "toothpaste tube toothbrush",
  "Pastas y Sopas": "pasta and soup",
  "Pastillas Potabilizadoras": "water purification tablets",
  "Pañales": "baby diapers pack",
  "Playeras": "folded t-shirts",
  "Protección Solar": "sunscreen lotion bottle",
  "Proteínas y Suplementos": "protein supplement powder",
  "Repelente de Insectos": "insect repellent spray",
  "Ropa Interior": "folded underwear",
  "Ropa de Abrigo": "winter jacket coat",
  "Sacos de Dormir": "sleeping bag",
  "Suministros Mascotas": "pet supplies",
  "Toallas Femeninas": "feminine hygiene pads box",
  "Toallas Húmedas": "baby wet wipes package plastic",
};
